---
- name: Converge
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Gather required subset of facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - architecture
          - system

  roles:
    - role: wzzrd.ghdl.downloader
      vars:
        downloader_organization: starship
        downloader_project: starship
        downloader_version: v1.21.1
        downloader_github_token: "{{ lookup('ansible.builtin.env', 'GITHUB_PAT') }}"
