---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy

platforms:
  - name: ubi9
    image: registry.access.redhat.com/ubi9/ubi-init:latest
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: "/usr/sbin/init"
    platform: linux/amd64

  - name: ubi10
    image: registry.access.redhat.com/ubi10/ubi-init:latest
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: "/usr/sbin/init"
    platform: linux/amd64

driver:
  name: podman
  options:
    managed: false
    login_cmd_template: "podman exec -it {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

provisioner:
  name: ansible
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    cleanup: cleanup.yml
    destroy: destroy.yml
  inventory:
    group_vars:
      all:
        downloader_github_token: "{{ lookup('ansible.builtin.env', 'GITHUB_PAT') }}"
    host_vars:
      ubi9:
        ansible_python_interpreter: /usr/bin/python3
      ubi10:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
